//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImLazy.Addins.Properties {
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImLazy.Addins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Any 的本地化字符串。
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 file 的本地化字符串。
        /// </summary>
        internal static string AnyFile {
            get {
                return ResourceManager.GetString("AnyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archieve 的本地化字符串。
        /// </summary>
        internal static string Archieve {
            get {
                return ResourceManager.GetString("Archieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 attribute 的本地化字符串。
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 audio 的本地化字符串。
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 condition matches 的本地化字符串。
        /// </summary>
        internal static string ConditionMatches {
            get {
                return ResourceManager.GetString("ConditionMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 contains 的本地化字符串。
        /// </summary>
        internal static string ContainsVerb {
            get {
                return ResourceManager.GetString("ContainsVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string CopyAction {
            get {
                return ResourceManager.GetString("CopyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteAction {
            get {
                return ResourceManager.GetString("DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 document 的本地化字符串。
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 equals 的本地化字符串。
        /// </summary>
        internal static string EqualVerb {
            get {
                return ResourceManager.GetString("EqualVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File extension 的本地化字符串。
        /// </summary>
        internal static string FileExtensionSubject {
            get {
                return ResourceManager.GetString("FileExtensionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name with extension 的本地化字符串。
        /// </summary>
        internal static string FileNameSubject {
            get {
                return ResourceManager.GetString("FileNameSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File type 的本地化字符串。
        /// </summary>
        internal static string FileTypeConditionAddin {
            get {
                return ResourceManager.GetString("FileTypeConditionAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File type 的本地化字符串。
        /// </summary>
        internal static string FileTypeSubject {
            get {
                return ResourceManager.GetString("FileTypeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder 的本地化字符串。
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GuitarPro tab 的本地化字符串。
        /// </summary>
        internal static string GuitarProTab {
            get {
                return ResourceManager.GetString("GuitarProTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is 的本地化字符串。
        /// </summary>
        internal static string Is {
            get {
                return ResourceManager.GetString("Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is 的本地化字符串。
        /// </summary>
        internal static string IsVerb {
            get {
                return ResourceManager.GetString("IsVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matches 的本地化字符串。
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata 的本地化字符串。
        /// </summary>
        internal static string MetadataConditionAddin {
            get {
                return ResourceManager.GetString("MetadataConditionAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        internal static string MoveAction {
            get {
                return ResourceManager.GetString("MoveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not matches 的本地化字符串。
        /// </summary>
        internal static string NotMatches {
            get {
                return ResourceManager.GetString("NotMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 picture 的本地化字符串。
        /// </summary>
        internal static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SimpleMetadataConditionAddin 的本地化字符串。
        /// </summary>
        internal static string SimpleMetadataConditionAddin {
            get {
                return ResourceManager.GetString("SimpleMetadataConditionAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 contains 的本地化字符串。
        /// </summary>
        internal static string smb_contains {
            get {
                return ResourceManager.GetString("smb_contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ends with 的本地化字符串。
        /// </summary>
        internal static string smb_ends_with {
            get {
                return ResourceManager.GetString("smb_ends_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 equals 的本地化字符串。
        /// </summary>
        internal static string smb_equals {
            get {
                return ResourceManager.GetString("smb_equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 not contains 的本地化字符串。
        /// </summary>
        internal static string smb_not_contains {
            get {
                return ResourceManager.GetString("smb_not_contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 not ends with 的本地化字符串。
        /// </summary>
        internal static string smb_not_ends_with {
            get {
                return ResourceManager.GetString("smb_not_ends_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 not equals 的本地化字符串。
        /// </summary>
        internal static string smb_not_equals {
            get {
                return ResourceManager.GetString("smb_not_equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 not starts with 的本地化字符串。
        /// </summary>
        internal static string smb_not_starts_with {
            get {
                return ResourceManager.GetString("smb_not_starts_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 starts with 的本地化字符串。
        /// </summary>
        internal static string smb_starts_with {
            get {
                return ResourceManager.GetString("smb_starts_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File extension 的本地化字符串。
        /// </summary>
        internal static string System_FileExtension {
            get {
                return ResourceManager.GetString("System_FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name 的本地化字符串。
        /// </summary>
        internal static string System_FileName {
            get {
                return ResourceManager.GetString("System_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string System_Size {
            get {
                return ResourceManager.GetString("System_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 video 的本地化字符串。
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When 的本地化字符串。
        /// </summary>
        internal static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
    }
}
